name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        env:
          PORT: ${{ vars.PORT }}
          ACCESS_TOKEN_SECRET: ${{ vars.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ vars.REFRESH_TOKEN_SECRET }}
          MONGO_URL: ${{ toJson(secrets.MONGO_URL) }}
        run: |
          touch .env
          echo PORT=$PORT >> .env
          echo MONGO_URL=$MONGO_URL >> .env
          echo ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET >> .env
          echo REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET >> .env

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        working-directory: .
        run: npm install

      - name: build
        working-directory: .
        run: npm run build

      - name: make zip file
        working-directory: .
        run: zip -r app.zip .env package.json ./dist

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Chat-back
          environment_name: Chat-back-env
          version_label: ${{ github.run_number }}
          use_existing_version_if_available: true
          region: ap-northeast-2
          deployment_package: app.zip
